version: '3.8'
services:
  mongodb:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE: mongodb://mongodb:27017/donmark
      PORT: 5000  
    depends_on:
      - mongodb

volumes:
  mongodb: {}
